### ISSUE TITLE
Bug in docs

### ISSUE THREAD

**Issue by 0-wiz-0** [oziphantom/QwakSNES#1]
In the 'To build' instructions in the readme, it says:
```
64tass.exe -a QWAKSNES.sfc -b -X -o qwakSNES.sfc
```
but it should be
```
64tass.exe -a QWAKSNES.asm -b -X -o qwakSNES.sfc
```
(`sfc` -> `asm`)
Please also mention that you need to do this from the `16bit` directory.
Thanks!

**Comment by oziphantom** [comment]
Whoops, thanks. 
Fixed it. 
Let me know if it needs to be improved some more.

**Comment by 0-wiz-0** [comment]
Looks good now, thanks!
